obj-m := kvm.o kvm-intel.o kvm-amd.o
kvm-objs := X-TIER/X-TIER_list.o X-TIER/X-TIER_memory.o \
	 ../../X-TIER/X-TIER.o \
	 X-TIER/X-TIER_inject.o X-TIER/X-TIER_kvm.o \
	 kvm_main.o x86.o mmu.o emulate.o irq.o i8259.o pmu.o \
	 lapic.o ioapic.o preempt.o i8254.o coalesced_mmio.o irq_comm.o \
	 timer.o eventfd.o assigned-dev.o compat-x86.o async_pf.o cpuid.o \
	 ../external-module-compat.o
ifeq ($(CONFIG_IOMMU_API),y)
kvm-objs += iommu.o
endif
kvm-intel-objs := vmx.o
kvm-amd-objs := svm.o

kvm-objs += ../srcu.o

CFLAGS_kvm_main.o = -DKVM_MAIN
